freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  install_script:
  - pkg update -f
  - pkg upgrade -fy
  - pkg install -y gtk-doc gettext-tools gmake gobject-introspection intltool pkgconf spidermonkey78 meson dbus cmake consolekit2
  script:
    - perl -pi -e 's,#!/usr/bin/perl -w,#!/usr/local/bin/perl -w,' src/polkitbackend/toarray.pl
    - meson setup 
      -D authfw=pam
      -D examples=true
      -D gtk_doc=true
      -D introspection=true
      -D man=true
      -D session_tracking=ConsoleKit
      -D tests=false
      builddir
    - meson compile -C builddir
